// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rho_marina
arma::vec rho_marina(arma::vec x, double cw);
RcppExport SEXP _mmlasso_rho_marina(SEXP xSEXP, SEXP cwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cw(cwSEXP);
    rcpp_result_gen = Rcpp::wrap(rho_marina(x, cw));
    return rcpp_result_gen;
END_RCPP
}
// rho_bisq
arma::vec rho_bisq(arma::vec x, double cw);
RcppExport SEXP _mmlasso_rho_bisq(SEXP xSEXP, SEXP cwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cw(cwSEXP);
    rcpp_result_gen = Rcpp::wrap(rho_bisq(x, cw));
    return rcpp_result_gen;
END_RCPP
}
// psi_marina
arma::vec psi_marina(arma::vec x, double cw);
RcppExport SEXP _mmlasso_psi_marina(SEXP xSEXP, SEXP cwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cw(cwSEXP);
    rcpp_result_gen = Rcpp::wrap(psi_marina(x, cw));
    return rcpp_result_gen;
END_RCPP
}
// weight_marina
arma::vec weight_marina(arma::vec x, double cw);
RcppExport SEXP _mmlasso_weight_marina(SEXP xSEXP, SEXP cwSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type cw(cwSEXP);
    rcpp_result_gen = Rcpp::wrap(weight_marina(x, cw));
    return rcpp_result_gen;
END_RCPP
}
// Mscale_mar
double Mscale_mar(arma::vec x, double b, double cc);
RcppExport SEXP _mmlasso_Mscale_mar(SEXP xSEXP, SEXP bSEXP, SEXP ccSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type b(bSEXP);
    Rcpp::traits::input_parameter< double >::type cc(ccSEXP);
    rcpp_result_gen = Rcpp::wrap(Mscale_mar(x, b, cc));
    return rcpp_result_gen;
END_RCPP
}
// scale_tau
double scale_tau(arma::vec x);
RcppExport SEXP _mmlasso_scale_tau(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(scale_tau(x));
    return rcpp_result_gen;
END_RCPP
}
// my_svdecon
List my_svdecon(arma::mat x);
RcppExport SEXP _mmlasso_my_svdecon(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(my_svdecon(x));
    return rcpp_result_gen;
END_RCPP
}
// SPCC
List SPCC(arma::mat x);
RcppExport SEXP _mmlasso_SPCC(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(SPCC(x));
    return rcpp_result_gen;
END_RCPP
}
// MMLassoCpp_ini
List MMLassoCpp_ini(arma::mat xx, arma::vec y, arma::vec beta_ini);
RcppExport SEXP _mmlasso_MMLassoCpp_ini(SEXP xxSEXP, SEXP ySEXP, SEXP beta_iniSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type xx(xxSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_ini(beta_iniSEXP);
    rcpp_result_gen = Rcpp::wrap(MMLassoCpp_ini(xx, y, beta_ini));
    return rcpp_result_gen;
END_RCPP
}
// MMLassoCpp1
List MMLassoCpp1(arma::mat x, arma::vec y, arma::vec beta_ini, double scale_ini, double c1);
RcppExport SEXP _mmlasso_MMLassoCpp1(SEXP xSEXP, SEXP ySEXP, SEXP beta_iniSEXP, SEXP scale_iniSEXP, SEXP c1SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_ini(beta_iniSEXP);
    Rcpp::traits::input_parameter< double >::type scale_ini(scale_iniSEXP);
    Rcpp::traits::input_parameter< double >::type c1(c1SEXP);
    rcpp_result_gen = Rcpp::wrap(MMLassoCpp1(x, y, beta_ini, scale_ini, c1));
    return rcpp_result_gen;
END_RCPP
}
// MMLassoCpp2
List MMLassoCpp2(arma::vec xjota, arma::vec yast, arma::vec beta_lars, arma::vec beta_o, arma::vec alpha);
RcppExport SEXP _mmlasso_MMLassoCpp2(SEXP xjotaSEXP, SEXP yastSEXP, SEXP beta_larsSEXP, SEXP beta_oSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type xjota(xjotaSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type yast(yastSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_lars(beta_larsSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_o(beta_oSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(MMLassoCpp2(xjota, yast, beta_lars, beta_o, alpha));
    return rcpp_result_gen;
END_RCPP
}
// rr_se
List rr_se(arma::mat X, arma::vec y, double lambda2, double deltaesc, double cc_scale, int nkeep, int niter, double epsilon);
RcppExport SEXP _mmlasso_rr_se(SEXP XSEXP, SEXP ySEXP, SEXP lambda2SEXP, SEXP deltaescSEXP, SEXP cc_scaleSEXP, SEXP nkeepSEXP, SEXP niterSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type lambda2(lambda2SEXP);
    Rcpp::traits::input_parameter< double >::type deltaesc(deltaescSEXP);
    Rcpp::traits::input_parameter< double >::type cc_scale(cc_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type nkeep(nkeepSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(rr_se(X, y, lambda2, deltaesc, cc_scale, nkeep, niter, epsilon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_mmlasso_rho_marina", (DL_FUNC) &_mmlasso_rho_marina, 2},
    {"_mmlasso_rho_bisq", (DL_FUNC) &_mmlasso_rho_bisq, 2},
    {"_mmlasso_psi_marina", (DL_FUNC) &_mmlasso_psi_marina, 2},
    {"_mmlasso_weight_marina", (DL_FUNC) &_mmlasso_weight_marina, 2},
    {"_mmlasso_Mscale_mar", (DL_FUNC) &_mmlasso_Mscale_mar, 3},
    {"_mmlasso_scale_tau", (DL_FUNC) &_mmlasso_scale_tau, 1},
    {"_mmlasso_my_svdecon", (DL_FUNC) &_mmlasso_my_svdecon, 1},
    {"_mmlasso_SPCC", (DL_FUNC) &_mmlasso_SPCC, 1},
    {"_mmlasso_MMLassoCpp_ini", (DL_FUNC) &_mmlasso_MMLassoCpp_ini, 3},
    {"_mmlasso_MMLassoCpp1", (DL_FUNC) &_mmlasso_MMLassoCpp1, 5},
    {"_mmlasso_MMLassoCpp2", (DL_FUNC) &_mmlasso_MMLassoCpp2, 5},
    {"_mmlasso_rr_se", (DL_FUNC) &_mmlasso_rr_se, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_mmlasso(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
