# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rho_marina <- function(x, cw) {
    .Call(`_mmlasso_rho_marina`, x, cw)
}

rho_bisq <- function(x, cw) {
    .Call(`_mmlasso_rho_bisq`, x, cw)
}

psi_marina <- function(x, cw) {
    .Call(`_mmlasso_psi_marina`, x, cw)
}

weight_marina <- function(x, cw) {
    .Call(`_mmlasso_weight_marina`, x, cw)
}

Mscale_mar <- function(x, b, cc) {
    .Call(`_mmlasso_Mscale_mar`, x, b, cc)
}

scale_tau <- function(x) {
    .Call(`_mmlasso_scale_tau`, x)
}

my_svdecon <- function(x) {
    .Call(`_mmlasso_my_svdecon`, x)
}

SPCC <- function(x) {
    .Call(`_mmlasso_SPCC`, x)
}

MMLassoCpp_ini <- function(xx, y, beta_ini) {
    .Call(`_mmlasso_MMLassoCpp_ini`, xx, y, beta_ini)
}

MMLassoCpp1 <- function(x, y, beta_ini, scale_ini, c1) {
    .Call(`_mmlasso_MMLassoCpp1`, x, y, beta_ini, scale_ini, c1)
}

MMLassoCpp2 <- function(xjota, yast, beta_lars, beta_o, alpha) {
    .Call(`_mmlasso_MMLassoCpp2`, xjota, yast, beta_lars, beta_o, alpha)
}

rr_se <- function(X, y, lambda2, deltaesc, cc_scale, nkeep, niter, epsilon) {
    .Call(`_mmlasso_rr_se`, X, y, lambda2, deltaesc, cc_scale, nkeep, niter, epsilon)
}

